---
title: "Motor_Trend_Car_Road_Tests"
author: "James Hancock"
date: "04 September 2016"
output: pdf_document
---
#Executive Summary

Motor Trend, an automobile trend magazine is interested in exploring the relationship between a set of variables and miles per gallon (MPG) outcome. In this project, I will analyze the mtcars dataset from the 1974 Motor Trend US magazine to answer the following questions:

-Is an automatic or manual transmission better for miles per gallon (MPG)?
-How different is the MPG between automatic and manual transmissions?

Using simple linear regression analysis, we determine that there is a signficant difference between the mean MPG for automatic and manual transmission cars.
Manual transmissions achieve a higher value of MPG compared to automatic transmission. This increase is approximately 1.8 MPG when switching from an automatic transmission to a manual one, with all else held constant.

#Data Processing

I begin by loading in the mtcars dataset and transforming certain variables into factors.

```{data(mtcars)
mtcars$cyl  <- factor(mtcars$cyl)
mtcars$vs   <- factor(mtcars$vs)
mtcars$gear <- factor(mtcars$gear)
mtcars$carb <- factor(mtcars$carb)
mtcars$am   <- factor(mtcars$am,labels=c("Automatic","Manual"))}
```
#Exploratory Analysis

Now I explore various relationships between variables of interest. First, I will plot the relationship between all the variables of the mtcars dataset.
From this plot i have learnt that the variables cyl, disp, hp, drat, wt, vs and am have a strong correlation with mpg, please see (Appendix - Figure 1).

In this analysis, I am interested in the effects of car transmission type on mpg Please see (Appendix - Figure 2). So, we look at the distribution of mpg for each level of am (Automatic or Manual) by plotting box plot.
This plot clearly depicts that manual transmissions tend to have higher MPG. This data is further analyzed and discussed in regression analysis section by fitting a linear model.

#Regression Analysis

In this section, i will build linear regression models using different variables in order to find the best fit and compare it with the base model which i have used anova. After model selection, i have also performed analysis of the residuals.

#Model building and selection

The initial model i have used includes all variables as predictors of mpg. Then I perform stepwise model selection in order to select significant predictors for the final, best model.
The step function will perform this selection by calling lm repeatedly to build multiple regression models and select the best variables from them using both forward selection and backward elimination methods using AIC algorithm.
This ensures that we have included useful variables while omitting ones that do not contribute significantly to predicting mpg.

```{initialmodel <- lm(mpg ~ ., data = mtcars)
bestmodel <- step(initialmodel, direction = "both")}
```
The best model obtained from the above computations shows that variables, cyl, wt and hp as confounders and am as the independent variable. 

Please see the summary details of the model below.

```{summary(bestmodel)}
```

##Summary of Best Model
## Residuals:
     Min      1Q   Median   3Q    Max 
    -3.939 -1.256 -0.401  1.125  5.051 
## Coefficients:
###          Estimate Std. Error t value Pr(>|t|)    
   (Intercept)  33.7083     2.6049   12.94  7.7e-13 ***
   cyl6         -3.0313     1.4073   -2.15   0.0407 *  
   cyl8         -2.1637     2.2843   -0.95   0.3523    
   hp           -0.0321     0.0137   -2.35   0.0269 *  
   wt           -2.4968     0.8856   -2.82   0.0091 ** 
   amManual      1.8092     1.3963    1.30   0.2065    
## Residual standard error: 2.41 on 26 degrees of freedom
## Multiple R-squared:  0.866,  Adjusted R-squared:  0.84 
## F-statistic: 33.6 on 5 and 26 DF,  p-value: 1.51e-10

The adjusted R-squared value of 0.84 which is the maximum obtained considering all combinations of variables. From these results we can conclude that more than 84% of the variability is explained by the above model.

Now we compare the base model with only am as the predictor variable and the best model which we obtained above containing confounder variables also.

```{basemodel <- lm(mpg ~ am, data = mtcars)
anova(basemodel, bestmodel)}
```
## Analysis of Variance Table
## Model 1: mpg ~ am
## Model 2: mpg ~ cyl + hp + wt + am
##   Res.Df RSS Df Sum of Sq    F  Pr(>F)    
## 1     30 721                              
## 2     26 151  4       570 24.5 1.7e-08 ***
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Looking at the above results, the p-value obtained is highly significant and we reject the null hypothesis that the confounder variables cyl, hp and wt don't contribute to the accuracy of the model.

#Model Residuals and Diagnostics

In this section, I have the residual plots of our regression model along with computation of regression diagnostics for the linear model. This helps me in examining the residuals and finding leverage points to find any potential problems with the model.

```{par(mfrow=c(2, 2))
plot(bestmodel)}
```
Following observations are made from the above plots.

- The points in the Residuals vs. Fitted plot are randomly scattered on the plot that verifies the independence condition.

- The Normal Q-Q plot consists of the points which mostly fall on the line indicating that the residuals are normally distributed.

- The Scale-Location plot consists of points scattered in a constant band pattern, indicating constant variance.

- There are some distinct points of interest (outliers or leverage points) in the top right of the plots that may indicate values of increased leverage of outliers.

#Statistical Inference

In this section, I perform a t-test on the two subsets of mpg data: manual and automatic transmission assuming that the transmission data has a normal distribution and tests the null hypothesis that they come from the same distribution. Based on the t-test results, I reject the null hypothesis that the mpg distributions for manual and automatic transmissions are the same.

```{"t.test"(mpg ~ am, data = mtcars)}
```


#Conclusions

Based on the analysis done in this project, I can conclude the following below

- Cars with Manual transmission get 1.8 more miles per gallon compared to cars with Automatic transmission. (1.8 adjusted for hp, cyl, and wt).

- mpg will decrease by 2.5 for every 1000 lb increase in wt.

- mpg decreases negligibly (only 0.32) with every increase of 10 in hp.

- If number of cylinders, cyl increases from 4 to 6 and 8, mpg will decrease by a factor of 3 and 2.2 respectively (adjusted by hp, wt, and am).

#Appendix

##Figure 1 - Pairs plot for the "mtcars" dataset

```{"pairs"(mpg ~ ., data = mtcars)}
```

##Figure 2 - Boxplot of miles per gallon by transmission type

```{"boxplot"(mpg ~ am, data = mtcars, col = (c("red","blue")), ylab = "Miles Per Gallon", xlab = "Transmission Type")}
```


